# Generated by Django 6.0.3 on 2026-07-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_profile_critical_alert_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="code",
            field=models.CharField(max_length=6),
        ),
    ]
