# Generated by Django 6.0.3 on 2026-07-11 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_alter_emergencycontact_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="reminder",
            name="duration_days",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reminder",
            name="frequency",
            field=models.CharField(
                choices=[("once", "Once"), ("daily", "Daily")],
                default="once",
                max_length=10,
            ),
        ),
    ]
